Updated the changes when the user...
fincity-india/nocode-saas pull request #360
Opened 2023-11-28 12:53 UTC by Surendhar1997

... wants to register with same mail id more than once.

2023-11-28 12:55 UTC, Surendhar1997 commented
Also add changes during the registration process handled the case when no client name given in request for generation unique client code.

2023-11-28 12:57 UTC, serialcoder13 requested changes
Just remove the log in the method

2023-11-28 12:57 UTC, serialcoder13 commented on security/src/main/java/com/fincity/security/dao/ClientDAO.java
> +				.log();
Remove Log

2023-11-29 09:04 UTC, serialcoder13 approved these changes
LGTM

2023-11-29 09:04 UTC, merged