Feat/clientUrls
fincity-india/nocode-saas pull request #365
Opened 2023-12-01 12:06 UTC by Sumitabhbiswas

2023-12-01 12:54 UTC, Surendhar1997 approved these changes
LGTM

2023-12-04 09:04 UTC, serialcoder13 requested changes
Please make those suggested changes.

2023-12-04 16:08 UTC, serialcoder13 requested changes
Please update the changes

2023-12-04 16:08 UTC, serialcoder13 commented on security/src/main/java/com/fincity/security/dao/ClientUrlDAO.java
> +		if (!clientId.equals(null))
you should check clientId != null. If the clientId is null you can't invoke equals.

2023-12-05 05:43 UTC, serialcoder13 approved these changes
LGTM

2023-12-05 05:43 UTC, merged